### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by stefanpenner** [BackburnerJS/backburner.js#103]
- [x] fix https://github.com/ebryn/backburner.js/pull/110
- [ ] bump version
- [ ] add changelog
- [ ] release npm
- [ ] release bower?

**Comment by jayphelps** [comment]
@stefanpenner I need backburner via npm, I can take this over the finish line. Is this list outdated or do we basically just need to create a CHANGELOG, bump the version, then release to npm/bower?

**Comment by stefanpenner** [comment]
> Is this list outdated

should be correct
