### ISSUE TITLE
Add a new run loop function to coalesce requests until timer ends

### ISSUE THREAD

**Issue by aaronbhansen** [BackburnerJS/backburner.js#127]
We are needing a new run loop function that works similar to debounce, but functions a little differently. 

How it would work is as follows:
- A call is made to the coalesce function and the method is run immediately. A timer is also started for that method signature.
- Each additional call cancels the current timer and creates a new one (like debounce). A counter is also incremented for each time the method signature is called.
- When the timer is complete, if the counter is greater than 0 (meaning the method was called more than once during the timeout period), the method is called a second time. 

Our use case is, we have a web socket that pushes data updates to the front end on any backend change. We want the first data update to fire immediately, but then coalesce all the remaining data updates until the timer expires. We find that we are updating the data several times on the backend (with various backend processes), but want to limit the number of requests on the front end until we know the changes are complete. 

Debounce and throttle don't meet this requirement. I looked at extending backburner locally, but that would require rewriting and implementing many of the internal functionality to add this new method. It would be much easier to add it in backburner directly. 

I'm adding an issue here, to see if I created a pull request, if this is something that you could see being used else where and would be pulled into backburner to make available for ember?

**Comment by mixonic** [comment]
This sounds like debounce with `immediate`. See:

* https://github.com/ebryn/backburner.js/blob/30d4f505e935f7b588317f94a489dbdf44ec3a0b/tests/debounce_test.js#L84
* https://github.com/ebryn/backburner.js/blob/30d4f505e935f7b588317f94a489dbdf44ec3a0b/lib/backburner.js#L298

Passing `true` for immediate runs the method right away, then debounces the 2nd to the nth calls.

**Comment by aaronbhansen** [comment]
It is close, but the difference is, if you set immediate to true, it only runs the method once and then debounces until the timer is cleared. I want two calls to the method, once immediately, and once when the timer clears if the method was called more than the initial immediate time. 

Using debounce with immediate, if the method was called 5 times before the timer cleared, the method would be called immediately and then not again until the timer cleared.

Using the proposed coalesce, if the method was called 5 times before the timer cleared, the method would be called immediately, and then once again when the timer cleared. Coalescing all the calls after the first into one final call at the end.

**Comment by runspired** [comment]
@aaronbhansen you get this coalescing behavior using `requestAnimationFrame` instead of `setTimeout`: see https://github.com/ebryn/backburner.js/pull/163

**Comment by rwjblue** [comment]
Closing this as it seems to have gone stale... I think in general, we would entertain a PR but I'm not certain that the use case for a specific `coalesce` method is general purpose enough to warrant inclusion.  

IMHO, a better path forward would be to distill what functionality would be required from Backburner to allow this to be relatively easily implemented in user-land?
