### ISSUE TITLE
how do I get the simple example to run standalone?

### ISSUE THREAD

**Issue by garris** [BackburnerJS/backburner.js#153]
Hi Guys,  How do I get backburner to run stand alone?   

I built using using `ember build` and included that file in a script tag on a vanilla .html page like so...

`<script src="vendor/backburner/dist/backburner.js"></script>`

The browser loads the file and I assumed I would see something like `Backburner` or maybe `BB` on the global scope -- but I don't.

What am I doing wrong?

**Comment by givanse** [comment]
https://github.com/ebryn/backburner.js#example-usage

**Comment by garris** [comment]
Correct. Not working -- with the build process I used:  `ember build`

**Comment by garris** [comment]
Ok, got the loading issue resolved with the help of the great and powerful @asakusuma!

PR forthcoming.
