### ISSUE TITLE
cancelling queued tasks should likely not splice/mutate the array

### ISSUE THREAD

**Issue by stefanpenner** [BackburnerJS/backburner.js#177]
Rather then costly array splicing, we should just mark the particular task as "cancelled" and then skip it in the flush.

relevant code: https://github.com/ebryn/backburner.js/blob/master/lib/backburner/queue.js#L190-L217

**Comment by rwjblue** [comment]
Sounds like a good idea to me, I'll try to poke at it today...

**Comment by rwjblue** [comment]
Submitted https://github.com/ebryn/backburner.js/pull/178 to get a baseline before messing with things...

**Comment by rwjblue** [comment]
replaced by #226
