### ISSUE TITLE
sinon.useFakeTimers in acceptance tests break if run.later is used

### ISSUE THREAD

**Issue by Gaurav0** [BackburnerJS/backburner.js#182]
See https://github.com/emberjs/ember.js/issues/14722

**Comment by alias-mac** [comment]
@rwjblue IMHO this can now be closed based on my comment here:
https://github.com/BackburnerJS/backburner.js/pull/264#issuecomment-331611010

For the given twiddle the simple fix is to call `this.clock.restore();` right before the `andThen()`.
