### ISSUE TITLE
`cancelTimers` crashes when there are debounced functions

### ISSUE THREAD

**Issue by eventualbuddha** [BackburnerJS/backburner.js#184]
#163 broke it, specifically [this commit](https://github.com/ebryn/backburner.js/pull/163/commits/66291441057e744c5f631eb94cf3273e2e7e55cb). See [discussion in Slack](https://embercommunity.slack.com/archives/general/p1485968041014032).

`clearItems` is being called without a context, so `this` inside it is null, leading to the error `Cannot read property '_platform' of undefined`. I believe the appropriate fix is to add tests covering this and change `clearItems()` to `clearItems.call(_this)`.

**Comment by eventualbuddha** [comment]
Reproduction: https://ember-twiddle.com/4a65efcd4b46d31ca8d298cc53db8761

**Comment by rwjblue** [comment]
> I believe the appropriate fix is to add tests covering this and change clearItems() to clearItems.call(_this)

Seems reasonable, mind working on it?

**Comment by eventualbuddha** [comment]
Either I or someone on my team will, yeah.

**Comment by eventualbuddha** [comment]
It's probably too much to hope that a fix for this would be included in a 2.4 release, right? Would it be included in a 2.8 LTS release?

**Comment by rwjblue** [comment]
Ember 2.4 is only receiving security related updates at this point. Ember 2.8 can still receive critical bugfixes, but (given the time it has taken to identify this as an issue) this doesn't seem super critical to me.

Once the fix lands here, I'm happy to land the fix in Ember canary (will be 2.13) and beta (will be 2.12), and I think it seems totally fine if someone wants to cherry-pick it into lts-2-8 branch, but I'm not sure we would do an actual patch release for it (though you could still use the prepublished assets from [the bower repo](https://github.com/components/ember/tree/lts-2-8)).

**Comment by alexhancock** [comment]
I've created https://github.com/ebryn/backburner.js/pull/185 to address this issue, let me know if you have any specific feedback on the changes there, @rwjblue

**Comment by rwjblue** [comment]
Was fixed by https://github.com/BackburnerJS/backburner.js/pull/185...
