### ISSUE TITLE
Remove impedance mismatches with ember

### ISSUE THREAD

**Issue by stefanpenner** [BackburnerJS/backburner.js#200]
### Why?

The impedance mismatch is largely with API naming, and function signatures. These result in extra code (setTimeout has ~80loc dedicated to this) and extra concepts that are confusing when teaching.

## idea:

* deprecate old behavior/methods + release
* with removed deprecated and old Behavior release a new major version

## details:

* drop + deprecate `bb.setTimeout` use `bb.later`. This lets us drop like ~80LOC re: API normalization: https://github.com/BackburnerJS/backburner.js/blob/master/lib/index.ts#L355-L412
* deprecate `defer*` in-favor of `schedule*`
* ??

**Comment by stefanpenner** [comment]
cc @lynchbomb / @krisselden

**Comment by lynchbomb** [comment]
https://github.com/BackburnerJS/backburner.js/commit/f22feb4b6d2651a00963177e9c8cba424f9cc4c0
