### ISSUE TITLE
Release + Update Ember

### ISSUE THREAD

**Issue by rwjblue** [BackburnerJS/backburner.js#239]
There have been quite a few changes here from the version that Ember is using to current master.  We should work towards solidifying things so that we can release and update Ember.  

I worry that letting things diverge to long will make upgrading more difficult, and may allow us to introduce subtle bugs here that Ember's tests may have helped catch...

**Comment by rwjblue** [comment]
@stefanpenner  / @krisselden - Any objections to releasing and bumping in Ember?

**Comment by stefanpenner** [comment]
i can cut a release right now.

**Comment by stefanpenner** [comment]
released as v1.0.0 🎉

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/pull/15282
