### ISSUE TITLE
drops later execution after sleep

### ISSUE THREAD

**Issue by makepanic** [BackburnerJS/backburner.js#353]
Hi,
we're seeing that some later invocations aren't executed on schedule after a system comes back from sleep.

The system has a long running `later` (every ~15min = 900000ms). After the system comes back from sleep, it triggers (caused by a failing network request) a 4s later execution which sometimes isn't getting executed.

![backburner-later-issue](https://user-images.githubusercontent.com/1205444/46610093-00e63b00-cb0a-11e8-909b-4e9c770a3ec6.png)

To debug the issue, we start a regular setTimeout in parallel to the later execution.
The setTimeout callback gets called 4s after executing it (see `[global]`). 

The `later` execution looks like this:

* `now + wait = 1539002635660` 
  * which is the same time the native setTimeout gets executed (~ Mon Oct 08 2018 14:43:55 GMT+0200 (Central European Summer Time))

https://github.com/BackburnerJS/backburner.js/blob/master/lib/index.ts#L646

* timers length is not 0 and searchTimer returns 6
  * this means `_reinstallTimerTimeout` isn't called

https://github.com/BackburnerJS/backburner.js/blob/master/lib/index.ts#L654

From the looks of it, this means that the scheduled timer isn't registered, which means it won't execute on time.
In the screenshot, we see the ember concurrency `timeout` never yields in the `4000` case (no `[concurrency] executing later cb 4000` logged).

My guess is that it isn't scheduled and the next timer that triggers is the longer running one.

**Comment by makepanic** [comment]
Sure i'll post the debugInfo once i can trigger the behavior again.
Here's the app flow for this issue:

Given:
1. app has long running timer (900000ms = 15min)

```js
while(true) {
    try {
        // do request
    } catch (e) {
        // handle error
        yield timeout(4000);
    }
}
```

2. user closes the laptop lid / sends the system into sleep
3. after a variable time, user opens the lid again
4. browser had failed requests during sleep and opening the lid
5. the returned timeout promise never resolves, as run.later never calls the callback

When placing a manual setTimeout near the run.later/timeout, it calls the callback as expected:

```js
    ...
} catch (e) {
    // handle error
    setTimeout(() => console.log('setTimeout executed'), 4000);
    yield timeout(4000);
}
```

During console.log debugging, i found that the initial `executeAt` calculation points to the correct expected time of timeout execution.
When looking at the code, it follow the branch flow where nothing gets scheduled.

My best guess is that [nothing is scheduled](https://github.com/BackburnerJS/backburner.js/blob/master/lib/index.ts#L658-L660) as the new timer isn't the "first" one:

```js
// we should be the new earliest timer if i == 0
if (i === 0) {
  this._reinstallTimerTimeout();
}
```

In the screenshot above, the new timeout got `i = 6`

**Comment by rwjblue** [comment]
> My best guess is that nothing is scheduled as the new timer isn't the "first" one:

Sounds reasonable, but what happened to the first ones timer? FWIW, this sounds similar (or possibly the same) as what @kanongil reported in #354...

**Comment by kanongil** [comment]
This might be another case than #354, if the browser somehow dropped the timer (which would be a browser bug).

**Comment by makepanic** [comment]
> This might be another case than #354, if the browser somehow dropped the timer (which would be a browser bug).

I don't think it's dropping the execution completely, it's backburner not scheduling a timer that triggers earlier.
I'm now trying to debug what the _timers list looks like when inserting the later timer after wakeup

**Comment by makepanic** [comment]
I think I now know what's the issue is.

**browser behavior** [1]

1. upon sleep, the browser pauses timeouts
2. upon awake, it resumes the timeout (without corrective early execution)

**in context of my app**

1. on boot backburner when the callback will fire (`executeAt`)

```
timers = [(now + 15min)]
```

2. on sleep, the timeout is paused causing `executeAt` to point to a wrong time
3. after >15min, on resume
  * schedule 4s later
  * backburner determines new timer as the second one and won't register an early `setTimeout`

```
timers = [(now + 15min), (now + 15min + sleep + 4s)]
```

4. after the resumed timer reaches 15min it'll work correctly again

[1] - i've only checked it in depth on linux chromium

**Comment by kanongil** [comment]
I just check on Chrome for Mac, and it behaves in the same way (pausing timeouts during system sleep). This is unfortunate.

I think the only reliable solution, is to reinstall the timer on each call to `_later()`. While this might look a bit weird on the already scheduled timers, it will ensure that new timers are handled properly.

**Comment by kanongil** [comment]
Your cheap solution would not work if it immediately goes to sleep, and wakes up slightly before the `executeAt`, and install the new timer. In that case it could still have to wait ~15 min to fire.
