### ISSUE TITLE
timer queues like setTimeout should enforce ordering

### ISSUE THREAD

**Issue by stefanpenner** [BackburnerJS/backburner.js#89]
see:
- https://github.com/emberjs/ember.js/issues/3559
- https://github.com/emberjs/ember.js/issues/3526

TL;DR underpowered devices can screw up orderings + devices revived from sleep often have time dilation or other crazy quirks.

**Comment by rwjblue** [comment]
This is a pretty old issue, I'm don't think we still support browsers that have the original issue...

@stefanpenner  - Closing for now, please reopen if I'm mistaken?
